import * as path from "path";

const LANGUAGE_MAP: Record<string, string> = {
	ada: "ada",
	ahk: "ahk",
	android: "android",
	angular: "angular",
	ansible: "ansible",
	applescript: "applescript",
	appveyor: "appveyor",
	arduino: "arduino",
	asciidoc: "asciidoc",
	asp: "asp",
	assembly: "assembly",
	astro: "astro",
	bat: "bat",
	bazel: "bazel",
	bicep: "bicep",
	brainfuck: "brainfuck",
	c: "c",
	c3: "c3",
	cargo: "cargo",
	circleci: "circleci",
	clojure: "clojure",
	cmake: "cmake",
	cobol: "cobol",
	coffee: "coffee",
	cpp: "cpp",
	crystal: "crystal",
	csharp: "csharp",
	csproj: "csproj",
	css: "css",
	cuda: "cuda",
	cursor: "cursor",
	cython: "cython",
	d: "d",
	dart: "dart",
	delphi: "delphi",
	dockerfile: "docker",
	dockercompose: "docker",
	elixir: "elixir",
	elm: "elm",
	erlang: "erlang",
	fortran: "fortran",
	fsharp: "fsharp",
	go: "go",
	gradle: "gradle",
	graphql: "graphql",
	groovy: "groovy",
	handlebars: "handlebars",
	haskell: "haskell",
	haxe: "haxe",
	html: "html",
	java: "java",
	javascript: "js",
	javascriptreact: "jsx",
	json: "json",
	jsonc: "json",
	julia: "julia",
	kotlin: "kotlin",
	latex: "tex",
	less: "less",
	lisp: "lisp",
	log: "log",
	lua: "lua",
	makefile: "makefile",
	markdown: "markdown",
	matlab: "matlab",
	objective_c: "objective-c",
	ocaml: "ocaml",
	pascal: "pascal",
	perl: "perl",
	php: "php",
	plaintext: "text",
	postcss: "postcss",
	powershell: "powershell",
	prolog: "prolog",
	protobuf: "protobuf",
	pug: "pug",
	purescript: "purescript",
	python: "python",
	qml: "qml",
	r: "r",
	razor: "razor",
	reason: "reasonml",
	restructuredtext: "restructuredtext",
	ruby: "ruby",
	rust: "rust",
	sass: "scss",
	scss: "scss",
	shaderlab: "hlsl",
	shellscript: "shell",
	smalltalk: "smalltalk",
	solidity: "solidity",
	sql: "sql",
	stylus: "stylus",
	svelte: "svelte",
	swift: "swift",
	systemverilog: "systemverilog",
	toml: "toml",
	tsx: "tsx",
	twig: "twig",
	typescript: "ts",
	typescriptreact: "tsx",
	vala: "vala",
	vb: "vb",
	vhdl: "vhdl",
	viml: "vim",
	vue: "vue",
	wasm: "wasm",
	xml: "xml",
	xsl: "xml",
	yaml: "yaml",
	zig: "zig",
};

// import.meta.dirname resolve to /out -> dirname gets the extension
const ICONS_DIR = path.join(path.dirname(import.meta.dirname), "assets", "icons");

export function getIconPath(languageId: string): string {
	const id = languageId.toLowerCase();
	const iconName = LANGUAGE_MAP[id] ?? id;
	return path.join(ICONS_DIR, `${iconName}.png`);
}